# path: discord_bot/cogs/_views_bump.py

"""
Wizard for /bump bot: ask for a Bot ID instead of a typed name, auto-fetch
the bot's real name/icon from Discord's public application RPC endpoint,
then hand off to a browser OAuth step (api/bump_oauth.py) so the invite
link can only ever be generated by us from the verified application_id —
never accepted as free-text — and the submission is tied to a real Discord
account that confirmed ownership, not just typed in blind.

Mirrors the step-checklist Components V2 pattern in _views_welcome.py.
"""

import logging
import secrets

import aiohttp
import discord

from config import DISCORD_OAUTH_CLIENT_ID, PUBLIC_BASE_URL
from database import db

logger = logging.getLogger(__name__)

RPC_URL = "https://discord.com/api/v10/applications/{app_id}/rpc"


async def _fetch_application(app_id: int) -> dict | None:
    """Public endpoint, no auth needed — returns name/icon/description for
    any application id that exists, whether or not it's "public"."""
    try:
        async with aiohttp.ClientSession() as session:
            async with session.get(RPC_URL.format(app_id=app_id), timeout=aiohttp.ClientTimeout(total=10)) as resp:
                if resp.status != 200:
                    return None
                return await resp.json()
    except Exception:
        return None


def _icon_url(app_data: dict) -> str | None:
    icon = app_data.get("icon")
    if not icon:
        return None
    return f"https://cdn.discordapp.com/app-icons/{app_data['id']}/{icon}.png"


async def _notify_submitter(client: discord.Client, user_id: int, bot_name: str, approved: bool) -> None:
    """Best-effort DM to whoever verified ownership, once a moderator acts
    on their submission — this runs in the gateway process (unlike the
    OAuth callback's admin DM), so a normal discord.py fetch_user works."""
    try:
        user = client.get_user(user_id) or await client.fetch_user(user_id)
        if approved:
            msg = f"✅ Your bot **{bot_name}** was approved and is now live on the bump network."
        else:
            msg = f"🚫 Your bot **{bot_name}** submission wasn't approved this time. You're welcome to submit again with `/bump bot`."
        await user.send(msg)
    except (discord.NotFound, discord.Forbidden, discord.HTTPException):
        pass


class BumpBotIdModal(discord.ui.Modal, title="Add a bot to the bump network"):
    bot_id = discord.ui.TextInput(label="Bot ID (right-click bot → Copy ID)", placeholder="e.g. 1234567890123456", max_length=25)
    description = discord.ui.TextInput(
        label="Short description (optional)", style=discord.TextStyle.paragraph,
        required=False, max_length=300,
    )

    def __init__(self, guild_id: int, clone_id: int | None, existing_listing_id: int | None = None):
        super().__init__()
        self.guild_id = guild_id
        self.clone_id = clone_id
        self.existing_listing_id = existing_listing_id

    async def on_submit(self, interaction: discord.Interaction):
        raw = str(self.bot_id.value).strip()
        if not raw.isdigit():
            await interaction.response.send_message("That doesn't look like a valid Bot ID — it should be all digits.", ephemeral=True)
            return
        app_id = int(raw)

        await interaction.response.defer(ephemeral=True)
        try:
            app_data = await _fetch_application(app_id)
            if not app_data:
                await interaction.followup.send(
                    "Couldn't find a bot with that ID. Double check it — right-click the bot in Discord and **Copy User ID** "
                    "(enable Developer Mode in Discord Settings → Advanced if you don't see that option).",
                    ephemeral=True,
                )
                return

            name = app_data.get("name", "Unknown bot")
            icon_url = _icon_url(app_data)
            desc = str(self.description.value).strip() or app_data.get("description") or f"{name} — a Discord bot."

            if not DISCORD_OAUTH_CLIENT_ID or not PUBLIC_BASE_URL:
                await interaction.followup.send(
                    "Ownership verification isn't set up on this bot yet — ask the bot owner to configure "
                    "`DISCORD_OAUTH_CLIENT_ID` / `PUBLIC_BASE_URL`.", ephemeral=True,
                )
                return

            state = secrets.token_urlsafe(24)
            await db.create_bump_oauth_state(
                state, self.guild_id, self.clone_id, interaction.user.id, app_id, name, icon_url, desc,
                tags=["community"], existing_listing_id=self.existing_listing_id,
            )

            verify_url = f"{PUBLIC_BASE_URL}/api/bump_oauth?state={state}"
            embed = discord.Embed(
                title=f"Found it: {name}",
                description=(
                    f"{desc}\n\n"
                    "Last step — sign in with Discord to confirm this is your bot. "
                    "This just verifies your identity; we generate the invite link ourselves so it "
                    "can never be swapped for something else."
                ),
            )
            if icon_url:
                embed.set_thumbnail(url=icon_url)
            view = discord.ui.View()
            view.add_item(discord.ui.Button(label="Verify & submit", style=discord.ButtonStyle.link, url=verify_url))
            await interaction.followup.send(embed=embed, view=view, ephemeral=True)
        except Exception:
            logger.exception("BumpBotIdModal.on_submit failed for app_id %s", app_id)
            try:
                await interaction.followup.send("Something went wrong looking that bot up — check the bot logs.", ephemeral=True)
            except discord.HTTPException:
                pass

    async def on_error(self, interaction: discord.Interaction, error: Exception) -> None:
        logger.exception("Unhandled error in BumpBotIdModal: %s", error)
        if not interaction.response.is_done():
            try:
                await interaction.response.send_message("Something went wrong — check the bot logs.", ephemeral=True)
            except discord.HTTPException:
                pass


class BumpBotStartView(discord.ui.View):
    """Single-button entry point posted by /bump bot — opens the modal."""

    def __init__(self, guild_id: int, clone_id: int | None, existing_listing_id: int | None = None):
        super().__init__(timeout=180)
        self.guild_id = guild_id
        self.clone_id = clone_id
        self.existing_listing_id = existing_listing_id

    @discord.ui.button(label="Enter Bot ID", style=discord.ButtonStyle.primary, emoji="🤖")
    async def start(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.send_modal(BumpBotIdModal(self.guild_id, self.clone_id, self.existing_listing_id))

    async def on_error(self, interaction: discord.Interaction, error: Exception, item: discord.ui.Item) -> None:
        logger.exception("Unhandled error in BumpBotStartView: %s", error)
        if not interaction.response.is_done():
            try:
                await interaction.response.send_message("Something went wrong — check the bot logs.", ephemeral=True)
            except discord.HTTPException:
                pass


class BumpReviewView(discord.ui.View):
    """Approve/reject buttons attached to each pending listing shown by
    /bumpadmin review. timeout=None since a moderator might not act on it
    the same session it was posted."""

    def __init__(self, listing_id: int):
        super().__init__(timeout=None)
        self.listing_id = listing_id

    @discord.ui.button(label="Approve", style=discord.ButtonStyle.success, emoji="✅")
    async def approve(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.defer(ephemeral=True)
        try:
            listing = await db.bump_review_listing(self.listing_id, approve=True)
        except Exception:
            logger.exception("bump_review_listing(approve) failed for listing %s", self.listing_id)
            if not interaction.response.is_done():
                await interaction.followup.send("Something went wrong approving this — check the bot logs.", ephemeral=True)
            return
        for item in self.children:
            item.disabled = True
        label = f"✅ Approved **{listing['name']}**." if listing else "Already handled (listing not found)."
        await interaction.edit_original_response(content=label, embed=None, view=self)
        if listing and listing.get("verified_owner_id"):
            await _notify_submitter(interaction.client, listing["verified_owner_id"], listing["name"], approved=True)

    @discord.ui.button(label="Reject", style=discord.ButtonStyle.danger, emoji="🚫")
    async def reject(self, interaction: discord.Interaction, button: discord.ui.Button):
        await interaction.response.defer(ephemeral=True)
        try:
            listing = await db.bump_review_listing(self.listing_id, approve=False)
        except Exception:
            logger.exception("bump_review_listing(reject) failed for listing %s", self.listing_id)
            if not interaction.response.is_done():
                await interaction.followup.send("Something went wrong rejecting this — check the bot logs.", ephemeral=True)
            return
        for item in self.children:
            item.disabled = True
        await interaction.edit_original_response(content="🚫 Rejected and removed.", embed=None, view=self)
        if listing and listing.get("verified_owner_id"):
            await _notify_submitter(interaction.client, listing["verified_owner_id"], listing["name"], approved=False)

    async def on_error(self, interaction: discord.Interaction, error: Exception, item: discord.ui.Item) -> None:
        logger.exception("Unhandled error in BumpReviewView (listing %s): %s", self.listing_id, error)
        if not interaction.response.is_done():
            try:
                await interaction.response.send_message("Something went wrong — check the bot logs.", ephemeral=True)
            except discord.HTTPException:
                pass
