export type Row = { cmd: string; syntax: string; desc: string; perm: string }
export type SubSection = { title: string; note?: string; rows: Row[]; footnote?: string }
export type Section = { id: string; title: string; intro?: string; rows?: Row[]; subs?: SubSection[] }

// Last content sync with modules/command_reference.py + cogs: see /manual page footer.
export const MANUAL_SECTIONS: Section[] = [
  {
    id: 'moderation',
    title: '1. Moderation',
    intro:
      'Every slash command in the bot, grouped by system, with exact syntax, what each option means, and who\u2019s allowed to use it. "Anyone" means no special permission is required. Where a permission is listed, Discord itself blocks anyone without it \u2014 the bot won\u2019t even let the command run.',
    rows: [
      { cmd: '/ban', syntax: '/ban member:@user reason:<text>', desc: 'Bans a member from the server', perm: 'Ban Members' },
      { cmd: '/unban', syntax: '/unban user_id:<id>', desc: 'Unbans a user by their Discord ID', perm: 'Ban Members' },
      { cmd: '/kick', syntax: '/kick member:@user reason:<text>', desc: 'Kicks a member from the server', perm: 'Kick Members' },
      { cmd: '/timeout', syntax: '/timeout member:@user duration:<minutes> reason:<text>', desc: 'Times out (mutes) a member for the given number of minutes', perm: 'Moderate Members' },
      { cmd: '/untimeout', syntax: '/untimeout member:@user', desc: 'Removes an active timeout early', perm: 'Moderate Members' },
      { cmd: '/warn', syntax: '/warn member:@user reason:<text>', desc: 'Issues a warning, logged against the member', perm: 'Moderate Members' },
      { cmd: '/unwarn', syntax: '/unwarn member:@user', desc: 'Clears all of a member\u2019s warnings', perm: 'Moderate Members' },
      { cmd: '/warns', syntax: '/warns [member:@user]', desc: 'Shows a member\u2019s warning count. Leave member blank to check yourself', perm: 'Anyone' },
      { cmd: '/modlogs', syntax: '/modlogs', desc: 'Shows the server\u2019s recent moderation action history (bans, kicks, timeouts, warns)', perm: 'Moderate Members' },
    ],
    subs: [
      {
        title: 'Auto-Moderation \u2014 /automod',
        rows: [
          { cmd: '/automod status', syntax: '/automod status', desc: 'Shows current auto-mod settings', perm: 'Manage Server' },
          { cmd: '/automod setup', syntax: '/automod setup', desc: 'Guided step-by-step wizard to configure auto-mod from scratch', perm: 'Manage Server' },
          { cmd: '/automod panel', syntax: '/automod panel', desc: 'Posts a button panel to toggle filters on/off', perm: 'Manage Server' },
          { cmd: '/automod toggle', syntax: '/automod toggle filter:<name> enabled:<on/off>', desc: 'Turns one specific filter on or off', perm: 'Manage Server' },
          { cmd: '/automod action', syntax: '/automod action', desc: 'Sets what happens when a filter is triggered (e.g. delete, warn, timeout)', perm: 'Manage Server' },
          { cmd: '/automod mentionthreshold', syntax: '/automod mentionthreshold', desc: 'Sets how many @mentions in a single message counts as mention-spam', perm: 'Manage Server' },
          { cmd: '/automod minaccountage', syntax: '/automod minaccountage', desc: 'Auto-kicks new joiners whose Discord account is younger than this (raid protection). Set to 0 to disable', perm: 'Manage Server' },
          { cmd: '/automod setlogchannel', syntax: '/automod setlogchannel', desc: 'Sets (or clears) the channel that auto-mod and moderation actions get logged to', perm: 'Manage Server' },
          { cmd: '/automod dashboard', syntax: '/automod dashboard', desc: 'Gives a link to configure auto-mod from a web dashboard instead of Discord', perm: 'Manage Server' },
          { cmd: '/automod bannedword add', syntax: '/automod bannedword add', desc: 'Adds a word or phrase to the blocked list', perm: 'Manage Server' },
          { cmd: '/automod bannedword preset', syntax: '/automod bannedword preset', desc: 'Bulk-loads a curated bad-words list into the filter in one go', perm: 'Manage Server' },
          { cmd: '/automod bannedword remove', syntax: '/automod bannedword remove', desc: 'Removes a word or phrase from the blocked list', perm: 'Manage Server' },
          { cmd: '/automod bannedword list', syntax: '/automod bannedword list', desc: 'Lists everything currently blocked', perm: 'Manage Server' },
          { cmd: '/automod owner (subgroup)', syntax: '\u2014', desc: 'Bot-owner-only controls for cleaning up automod reminder DMs the bot has sent', perm: 'Bot Owner' },
        ],
      },
      {
        title: 'Join Verification \u2014 /setupverification',
        note:
          'Anti-raid gate \u2014 new members get an Unverified role until they pass a captcha or button click. Added here: the join-DM "Turn on" shortcut for this can\u2019t open its picker inline (channel/role selects only resolve inside a real server channel), so it now just points you at running this command directly in the server.',
        rows: [
          { cmd: '/setupverification', syntax: '/setupverification', desc: 'Opens the setup wizard \u2014 pick mode (captcha or button), verify channel, unverified role, and verified role, then hit Lock down & enable', perm: 'Manage Server' },
        ],
      },
    ],
  },
  {
    id: 'server-setup',
    title: '2. Server Setup & Configuration',
    rows: [
      { cmd: '/serversetup', syntax: '/serversetup', desc: 'The umbrella guided setup wizard for the bot\u2019s main features', perm: 'Anyone (admin-relevant)' },
      { cmd: '/setup channels', syntax: '/setup channels', desc: 'Suggests and creates commonly-useful channels for a new server', perm: 'Manage Server (implied)' },
      { cmd: '/setup downloadhub', syntax: '/setup downloadhub', desc: 'Sets up a channel where anyone can submit music/video links for download', perm: 'Manage Server (implied)' },
    ],
    subs: [
      {
        title: 'Welcome Cards \u2014 /welcome',
        rows: [
          { cmd: '/welcome enable', syntax: '/welcome enable', desc: 'Turns on welcome cards for a chosen channel', perm: 'Manage Server' },
          { cmd: '/welcome disable', syntax: '/welcome disable', desc: 'Turns welcome cards off', perm: 'Manage Server' },
          { cmd: '/welcome message', syntax: '/welcome message', desc: 'Sets the welcome text. Supports placeholders {member}, {guild}, {count}', perm: 'Manage Server' },
          { cmd: '/welcome colors', syntax: '/welcome colors', desc: 'Sets the card\u2019s background/accent colors (hex like #2b2d31, or a name like blurple)', perm: 'Manage Server' },
          { cmd: '/welcome sticker', syntax: '/welcome sticker', desc: 'Sets or removes the GIF/sticker shown after the welcome card', perm: 'Manage Server' },
          { cmd: '/welcome buypack', syntax: '/welcome buypack', desc: 'Paid. Buys the premium welcome-card pack (extra looks) once for the whole server', perm: 'Manage Server' },
          { cmd: '/welcome buyultra', syntax: '/welcome buyultra', desc: 'Paid. Buys the Ultra pack, which lets you upload your own image as the card background', perm: 'Manage Server' },
          { cmd: '/welcome custombg', syntax: '/welcome custombg', desc: '(Ultra pack only) Sets the welcome card background to your own PNG/JPEG', perm: 'Manage Server' },
          { cmd: '/welcome theme', syntax: '/welcome theme', desc: 'Picks which welcome-card visual theme the server uses', perm: 'Manage Server' },
          { cmd: '/welcome style', syntax: '/welcome style', desc: 'Switches the card between an animated sticker or a static image', perm: 'Manage Server' },
          { cmd: '/welcome setup', syntax: '/welcome setup', desc: 'Interactive wizard to set the whole thing up step by step', perm: 'Manage Server' },
          { cmd: '/welcome preview', syntax: '/welcome preview', desc: 'Shows you what the welcome card would look like for you right now', perm: 'Anyone' },
        ],
        footnote: 'All /welcome subcommands need Manage Server, except /welcome preview which anyone can run.',
      },
      {
        title: 'Reaction Roles \u2014 /reactionrole',
        rows: [
          { cmd: '/reactionrole create', syntax: '/reactionrole create title:<text> description:<text>', desc: 'Posts a new, empty reaction-role panel in the current channel', perm: 'Manage Roles' },
          { cmd: '/reactionrole add', syntax: '/reactionrole add message_id:<id> role:<role> label:<text> emoji:<optional>', desc: 'Adds a role button to an existing panel', perm: 'Manage Roles' },
          { cmd: '/reactionrole remove', syntax: '/reactionrole remove message_id:<id> role:<role>', desc: 'Removes a role button from a panel', perm: 'Manage Roles' },
          { cmd: '/reactionrole list', syntax: '/reactionrole list', desc: 'Lists every reaction-role panel in the server', perm: 'Manage Roles' },
        ],
        footnote: 'Needs Manage Roles.',
      },
      {
        title: 'Leveling / XP',
        rows: [
          { cmd: '/rank', syntax: '/rank [member:@user]', desc: 'Shows your (or someone\u2019s) level and XP', perm: 'Anyone' },
          { cmd: '/leaderboard', syntax: '/leaderboard', desc: 'Shows the server\u2019s top 10 XP earners', perm: 'Anyone' },
          { cmd: '/levelrole setup', syntax: '/levelrole setup', desc: 'Guided wizard to configure level-up role rewards', perm: 'Manage Roles' },
          { cmd: '/levelrole add', syntax: '/levelrole add', desc: 'Grants a role automatically once a member hits a given level', perm: 'Manage Roles' },
          { cmd: '/levelrole remove', syntax: '/levelrole remove', desc: 'Removes a level-up role reward', perm: 'Manage Roles' },
          { cmd: '/levelrole list', syntax: '/levelrole list', desc: 'Lists configured level-up role rewards', perm: 'Manage Roles' },
          { cmd: '/voicexp settings', syntax: '/voicexp settings', desc: 'Shows current voice-channel XP settings', perm: 'Manage Server' },
          { cmd: '/voicexp toggle', syntax: '/voicexp toggle', desc: 'Enables/disables voice XP for the server', perm: 'Manage Server' },
          { cmd: '/voicexp rate', syntax: '/voicexp rate', desc: 'Sets how much XP is earned per minute spent in voice', perm: 'Manage Server' },
          { cmd: '/voicexp afk', syntax: '/voicexp afk', desc: 'Sets whether time in the AFK channel counts toward XP', perm: 'Manage Server' },
        ],
      },
      {
        title: 'Starboard \u2014 /starboard',
        rows: [
          { cmd: '/starboard community', syntax: '/starboard community', desc: 'Guided wizard that sets up starboard and suggestions together', perm: 'Manage Server' },
          { cmd: '/starboard setup', syntax: '/starboard setup', desc: 'Sets the starboard channel and the star-count threshold', perm: 'Manage Server' },
          { cmd: '/starboard emoji', syntax: '/starboard emoji', desc: 'Sets which emoji reaction counts toward the starboard', perm: 'Manage Server' },
          { cmd: '/starboard settings', syntax: '/starboard settings', desc: 'Shows current starboard settings', perm: 'Manage Server' },
          { cmd: '/starboard disable', syntax: '/starboard disable', desc: 'Turns the starboard off', perm: 'Manage Server' },
        ],
        footnote: 'All need Manage Server.',
      },
      {
        title: 'Tickets \u2014 /ticket',
        rows: [{ cmd: '/ticket setup', syntax: '/ticket setup', desc: 'Guided step-by-step wizard to set up the support-ticket system', perm: 'Manage Channels' }],
        footnote: 'Needs Manage Channels.',
      },
      {
        title: 'Giveaways \u2014 /giveaway',
        rows: [
          { cmd: '/giveaway setup', syntax: '/giveaway setup', desc: 'Guided wizard to create a giveaway', perm: 'Manage Server' },
          { cmd: '/giveaway start', syntax: '/giveaway start prize:<text> duration:<e.g. 1h, 30m, 2d12h> winners:<n>', desc: 'Starts a giveaway directly', perm: 'Manage Server' },
          { cmd: '/giveaway reroll', syntax: '/giveaway reroll message_id:<id>', desc: 'Rerolls the winner(s) of an ended giveaway', perm: 'Manage Server' },
        ],
        footnote: 'Needs Manage Server.',
      },
      {
        title: 'Scheduled Messages \u2014 /schedule',
        rows: [
          { cmd: '/schedule once', syntax: '/schedule once channel:#chan delay:<e.g. 2h, 30m, 1d> text:<text>', desc: 'Sends a message once, after a delay', perm: 'Manage Server' },
          { cmd: '/schedule recurring', syntax: '/schedule recurring channel:#chan interval:<e.g. 1d, 12h, 30m> text:<text>', desc: 'Reposts a message on a fixed interval', perm: 'Manage Server' },
          { cmd: '/schedule daily', syntax: '/schedule daily channel:#chan time_utc:<24h UTC, e.g. 09:00> text:<text>', desc: 'Posts a message once every day at a set UTC time', perm: 'Manage Server' },
          { cmd: '/schedule list', syntax: '/schedule list', desc: 'Lists every scheduled message in the server', perm: 'Manage Server' },
          { cmd: '/schedule cancel', syntax: '/schedule cancel schedule_id:<#>', desc: 'Cancels a scheduled message (id shown by /schedule list)', perm: 'Manage Server' },
        ],
        footnote:
          'Needs Manage Server. Related, standalone command: /announce channel:#chan message:<text> time:<when> schedules a one-off announcement; /announcements lists them; /cancelannouncement id:<id> cancels one. All need Manage Server.',
      },
      {
        title: 'Suggestions \u2014 /suggestions',
        rows: [
          { cmd: '/suggest', syntax: '/suggest text:<text>', desc: 'Submits a suggestion for staff/members to vote on', perm: 'Anyone' },
          { cmd: '/suggestions logchannel', syntax: '/suggestions logchannel', desc: 'Sets the channel approved suggestions get logged to', perm: 'Manage Server' },
        ],
      },
      {
        title: 'Invites',
        rows: [{ cmd: '/invites setup', syntax: '/invites setup', desc: 'Posts (or re-posts) the invite-tracker setup wizard', perm: 'Manage Server' }],
      },
      {
        title: 'Link Buttons \u2014 /linkbutton',
        rows: [
          { cmd: '/linkbutton add', syntax: '/linkbutton add label:<text> url:<https://...>', desc: 'Adds a custom labeled link button (e.g. "Join Our Channel" \u2192 a URL)', perm: 'Manage Server' },
          { cmd: '/linkbutton list', syntax: '/linkbutton list', desc: 'Lists the server\u2019s configured link buttons', perm: 'Manage Server' },
          { cmd: '/linkbutton remove', syntax: '/linkbutton remove label:<text>', desc: 'Removes a button by its exact label', perm: 'Manage Server' },
          { cmd: '/linkbutton panel', syntax: '/linkbutton panel', desc: 'Posts all configured link buttons as a message in the current channel', perm: 'Manage Server' },
        ],
        footnote: 'Needs Manage Server.',
      },
      {
        title: 'Autoresponder & Analytics',
        rows: [
          { cmd: '/autoresponder ...', syntax: '/autoresponder ...', desc: 'Manage automatic keyword\u2192reply responses', perm: 'Manage Server' },
          { cmd: '/serveranalytics', syntax: '/serveranalytics', desc: 'Snapshot of this server\u2019s size, activity, and growth suggestions', perm: 'Anyone' },
        ],
      },
      {
        title: 'Roast / Ship (fun automation)',
        rows: [
          { cmd: '/setup roastme', syntax: '/setup roastme', desc: 'Requests the bot roast a member \u2014 needs an admin\u2019s approval before it posts', perm: '' },
          { cmd: '/setup roaststart', syntax: '/setup roaststart', desc: 'Manually starts a roast battle immediately, skipping the normal wait', perm: '' },
          { cmd: '/setup roast', syntax: '/setup roast', desc: 'Configures the auto-roast trigger settings for the server', perm: '' },
          { cmd: '/setup shiptrigger', syntax: '/setup shiptrigger', desc: 'Manually "ships" (pairs up) two currently-active members right now', perm: '' },
          { cmd: '/setup shipconfig', syntax: '/setup shipconfig', desc: 'Configures the random shipping feature', perm: '' },
          { cmd: '/arena enable', syntax: '/arena enable', desc: 'Opts this server into inter-server roast battles', perm: 'Admin' },
          { cmd: '/arena disable', syntax: '/arena disable', desc: 'Opts this server out', perm: 'Admin' },
          { cmd: '/arena status', syntax: '/arena status', desc: 'Shows this server\u2019s roast-battle status', perm: 'Anyone' },
        ],
      },
    ],
  },
  {
    id: 'premium',
    title: '3. Premium (server monetization)',
    rows: [
      { cmd: '/pay', syntax: '/pay group:<name>', desc: 'Pays to unlock a Premium role in this server', perm: 'Anyone' },
      { cmd: '/status', syntax: '/status', desc: 'Checks your own premium payment status in this server', perm: 'Anyone' },
      { cmd: '/createpremium', syntax: '/createpremium ...', desc: 'Creates a new premium group (name, price, role) for this server', perm: 'Manage Server' },
      { cmd: '/listpremium', syntax: '/listpremium', desc: 'Lists this server\u2019s premium groups', perm: 'Anyone' },
      { cmd: '/premiumadmin', syntax: '/premiumadmin', desc: 'Manage premium groups from a dropdown menu instead of typing ids', perm: 'Admin (implied)' },
      { cmd: '/editpremium', syntax: '/editpremium group_id:<id> ...', desc: 'Edits an existing premium group\u2019s name/price/role', perm: 'Manage Server' },
      { cmd: '/togglepremium', syntax: '/togglepremium group_id:<id> active:<true/false>', desc: 'Enables/disables a group; disabled groups don\u2019t show in /pay', perm: 'Manage Server' },
      { cmd: '/verify', syntax: '/verify member:@user group:<name>', desc: 'Manually marks someone as paid, bypassing payment', perm: 'Manage Server' },
    ],
  },
  {
    id: 'economy',
    title: '4. Economy & Games',
    rows: [
      { cmd: '/economy daily', syntax: '/economy daily', desc: 'Claims your daily currency bonus', perm: 'Anyone' },
      { cmd: '/economy work', syntax: '/economy work', desc: 'Works a shift for currency', perm: 'Anyone' },
      { cmd: '/economy beg', syntax: '/economy beg', desc: 'Begs for spare change', perm: 'Anyone' },
      { cmd: '/economy balance', syntax: '/economy balance [member:@user]', desc: 'Checks your (or someone\u2019s) balance', perm: 'Anyone' },
      { cmd: '/economy leaderboard', syntax: '/economy leaderboard', desc: 'Shows the server\u2019s richest members', perm: 'Anyone' },
      { cmd: '/economy coinflip', syntax: '/economy coinflip amount:<n> choice:<heads/tails>', desc: 'Bets currency on a coin flip', perm: 'Anyone' },
      { cmd: '/economy rob', syntax: '/economy rob member:@user', desc: 'Attempts to rob another member', perm: 'Anyone' },
      { cmd: '/economy buy', syntax: '/economy buy item_id:<# from /shop list>', desc: 'Buys an item from the shop', perm: 'Anyone' },
      { cmd: '/economy vote', syntax: '/economy vote', desc: 'Votes for the bot for a currency bonus', perm: 'Anyone' },
      { cmd: '/economy watchad', syntax: '/economy watchad', desc: 'Views a sponsor message for a currency bonus', perm: 'Anyone' },
      { cmd: '/shop list', syntax: '/shop list', desc: 'Lists items available in the shop', perm: 'Anyone' },
      { cmd: '/shop add', syntax: '/shop add', desc: 'Adds an item to the shop', perm: 'Admin' },
      { cmd: '/shop remove', syntax: '/shop remove', desc: 'Removes an item from the shop', perm: 'Admin' },
      { cmd: '/ecoconfig setup', syntax: '/ecoconfig setup', desc: 'Guided wizard to set up the server\u2019s economy', perm: 'Manage Server' },
      { cmd: '/ecoconfig currency', syntax: '/ecoconfig currency', desc: 'Sets the currency\u2019s name and symbol', perm: 'Manage Server' },
      { cmd: '/ecoconfig vote', syntax: '/ecoconfig vote', desc: 'Configures the vote-bonus mechanic (top.gg-style)', perm: 'Manage Server' },
      { cmd: '/ecoconfig ads', syntax: '/ecoconfig ads', desc: 'Configures the sponsor-embed bonus mechanic', perm: 'Manage Server' },
    ],
    subs: [
      {
        title: 'Heist Wars',
        rows: [
          { cmd: '/heist', syntax: '/heist', desc: 'Opens the Heist Wars operations console \u2014 the hub for planning/running heists', perm: 'Anyone' },
          { cmd: '/inventory', syntax: '/inventory', desc: 'Views your Heist Wars inventory', perm: 'Anyone' },
          { cmd: '/loadout', syntax: '/loadout', desc: 'Manage your equipped tools and cosmetics', perm: 'Anyone' },
        ],
      },
      {
        title: 'Trading Cards \u2014 /card',
        rows: [
          { cmd: '/card daily', syntax: '/card daily', desc: 'Claims your free daily card pull', perm: 'Anyone' },
          { cmd: '/card pack', syntax: '/card pack', desc: 'Buys a card pack with Card Coins', perm: 'Anyone' },
          { cmd: '/card inventory', syntax: '/card inventory', desc: 'Views your card collection', perm: 'Anyone' },
          { cmd: '/card coins', syntax: '/card coins', desc: 'Checks your Card Coins balance', perm: 'Anyone' },
          { cmd: '/card sell', syntax: '/card sell', desc: 'Lists one of your cards for sale on the marketplace', perm: 'Anyone' },
          { cmd: '/card listings', syntax: '/card listings', desc: 'Views/cancels your active marketplace listings', perm: 'Anyone' },
          { cmd: '/card cancel', syntax: '/card cancel', desc: 'Cancels one of your marketplace listings', perm: 'Anyone' },
          { cmd: '/card watch', syntax: '/card watch', desc: 'Notifies you next time a specific card is listed', perm: 'Anyone' },
          { cmd: '/card market', syntax: '/card market', desc: 'Browses the cross-server card marketplace', perm: 'Anyone' },
        ],
        footnote: 'All anyone can use.',
      },
    ],
  },
  {
    id: 'ai-tools',
    title: '5. AI Tools',
    rows: [
      { cmd: '/aichat', syntax: '/aichat message:<text>', desc: 'Chats with the AI \u2014 anime questions, recommendations, or general conversation', perm: 'Anyone' },
      { cmd: '/newchat', syntax: '/newchat', desc: 'Starts a fresh AI conversation, clearing prior context', perm: 'Anyone' },
      { cmd: '/endchat', syntax: '/endchat', desc: 'Ends your active AI conversation', perm: 'Anyone' },
      { cmd: '/aiimage', syntax: '/aiimage prompt:<text> style:<anime/realistic/3d>', desc: 'Generates an image from a text prompt', perm: 'Anyone' },
      { cmd: '/aistatus', syntax: '/aistatus', desc: 'Checks your daily AI usage', perm: 'Anyone' },
    ],
    subs: [
      {
        title: 'AI Store \u2014 /aistore (paid AI personas)',
        rows: [
          { cmd: '/aistore credits', syntax: '/aistore credits', desc: 'Checks your AI Store credit balance', perm: 'Anyone' },
          { cmd: '/aistore topup', syntax: '/aistore topup', desc: 'Buys AI Store credits with GHS', perm: 'Anyone' },
          { cmd: '/aistore newchat', syntax: '/aistore newchat provider:<name>', desc: 'Starts a new AI Store conversation with a chosen provider/persona', perm: 'Anyone' },
          { cmd: '/aistore ask', syntax: '/aistore ask message:<text>', desc: 'Sends a message in your active AI Store conversation', perm: 'Anyone' },
          { cmd: '/aistore endchat', syntax: '/aistore endchat', desc: 'Ends your active AI Store conversation', perm: 'Anyone' },
          { cmd: '/aistore history', syntax: '/aistore history', desc: 'Views your recent AI Store transactions', perm: 'Anyone' },
          { cmd: '/aistore browse', syntax: '/aistore browse search:<optional> category:<optional>', desc: 'Browses AI assistant listings', perm: 'Anyone' },
          { cmd: '/aistore sell', syntax: '/aistore sell name:<text> description:<text> system_prompt:<text> ...', desc: 'Lists your own AI persona for sale in the store', perm: 'Anyone' },
          { cmd: '/aistore mylistings', syntax: '/aistore mylistings', desc: 'Views your own AI Store listings', perm: 'Anyone' },
          { cmd: '/aistore boost', syntax: '/aistore boost listing_id:<id>', desc: 'Pays to boost a listing\u2019s placement', perm: 'Anyone' },
          { cmd: '/aistore flagbad', syntax: '/aistore flagbad', desc: 'Reports your last AI response as broken and requests a refund', perm: 'Anyone' },
          { cmd: '/aistore reviewqueue', syntax: '/aistore reviewqueue action:<approve/reject> listing_id:<id>', desc: 'Reviews listings flagged for human review', perm: 'Admin' },
          { cmd: '/aistore refundqueue', syntax: '/aistore refundqueue action:<approve/deny> refund_id:<id>', desc: 'Reviews pending refund requests', perm: 'Admin' },
          { cmd: '/aistore menu', syntax: '/aistore menu', desc: 'Posts a button-based menu for the AI Store as a backup to typing commands', perm: 'Anyone' },
        ],
      },
    ],
  },
  {
    id: 'media-connect',
    title: '6. Media Connect (Plex / Jellyfin / Google Drive)',
    rows: [
      { cmd: '/connect subscribe', syntax: '/connect subscribe', desc: 'Paid ($2/month). Subscribes to Media Connect', perm: 'Anyone' },
      { cmd: '/connect status', syntax: '/connect status', desc: 'Checks your Media Connect subscription status', perm: 'Anyone' },
      { cmd: '/connect jellyfin', syntax: '/connect jellyfin server_url:<url> api_key:<key>', desc: 'Connects your own Jellyfin server', perm: 'Anyone' },
      { cmd: '/connect plex', syntax: '/connect plex', desc: 'Connects your own Plex server', perm: 'Anyone' },
      { cmd: '/connect gdrive', syntax: '/connect gdrive', desc: 'Connects a Google Drive folder you own', perm: 'Anyone' },
      { cmd: '/connect disconnect', syntax: '/connect disconnect source:<which>', desc: 'Disconnects a media source and forgets its credentials', perm: 'Anyone' },
      { cmd: '/movie search', syntax: '/movie search title:<text>', desc: 'Searches your connected library', perm: 'Anyone' },
      { cmd: '/movie play', syntax: '/movie play item_id:<id from search/library>', desc: 'Gets a private playback link for an item in your library', perm: 'Anyone' },
      { cmd: '/movie library', syntax: '/movie library', desc: 'Lists everything in your connected library', perm: 'Anyone' },
      { cmd: '/download', syntax: '/download url:<link>', desc: 'Downloads audio/video from a supported link (e.g. YouTube)', perm: 'Anyone' },
      { cmd: '/currency', syntax: '/currency currency:<code>', desc: 'Sets your preferred display currency for paid features across the bot', perm: 'Anyone' },
    ],
  },
  {
    id: 'discovery-utility',
    title: '7. Discovery & Utility',
    rows: [
      { cmd: '/discover', syntax: '/discover', desc: 'Browses anime by category', perm: 'Anyone' },
      { cmd: '/search', syntax: '/search query:<name>', desc: 'Searches for an anime by name', perm: 'Anyone' },
      { cmd: '/animecategory list', syntax: '/animecategory list', desc: 'Lists your saved anime categories', perm: 'Anyone' },
      { cmd: '/animecategory new', syntax: '/animecategory new', desc: 'Creates a new saved anime category', perm: 'Anyone' },
      { cmd: '/imagesearch', syntax: '/imagesearch', desc: 'Reverse image search \u2014 finds where an uploaded/linked image is from', perm: 'Anyone' },
      { cmd: '/news', syntax: '/news topic:<text>', desc: 'Gets top headlines about a topic', perm: 'Anyone' },
      { cmd: '/convert', syntax: '/convert amount:<n> from:<cur> to:<cur>', desc: 'Converts an amount between currencies', perm: 'Anyone' },
      { cmd: '/stock', syntax: '/stock symbol:<ticker>', desc: 'Gets a stock\u2019s current price and recent change', perm: 'Anyone' },
      { cmd: '/crypto', syntax: '/crypto symbol:<coin>', desc: 'Gets a cryptocurrency\u2019s current price', perm: 'Anyone' },
      { cmd: '/alert set', syntax: '/alert set coin:<id, e.g. bitcoin> price:<usd> direction:<above/below>', desc: 'Sets a price alert for a coin', perm: 'Anyone' },
      { cmd: '/alert list', syntax: '/alert list', desc: 'Shows your active price alerts', perm: 'Anyone' },
      { cmd: '/alert remove', syntax: '/alert remove coin:<id>', desc: 'Removes your alert for a specific coin', perm: 'Anyone' },
      { cmd: '/alert clear', syntax: '/alert clear', desc: 'Removes all your alerts', perm: 'Anyone' },
      { cmd: '/language', syntax: '/language', desc: 'Chooses the language the bot replies to you in', perm: 'Anyone' },
      { cmd: '/feedback', syntax: '/feedback message:<text>', desc: 'Sends feedback/a suggestion straight to the bot owner', perm: 'Anyone' },
      { cmd: '/viewfeedback', syntax: '/viewfeedback', desc: 'Views recently submitted feedback', perm: 'Bot Owner' },
      { cmd: '/help', syntax: '/help', desc: 'Shows everything the bot can do, organized by category', perm: 'Anyone' },
      { cmd: '/invite', syntax: '/invite', desc: 'Gets the bot\u2019s own invite link so you can add it elsewhere', perm: 'Anyone' },
    ],
    subs: [
      {
        title: 'Submissions (catalog)',
        rows: [
          { cmd: '/submit', syntax: '/submit', desc: 'Submits an anime/movie for the catalog', perm: 'Anyone' },
          { cmd: '/submissions pending', syntax: '/submissions pending', desc: 'Lists submissions awaiting review', perm: 'Manage Server' },
          { cmd: '/submissions review', syntax: '/submissions review', desc: 'Reviews pending submissions from a dropdown', perm: 'Manage Server' },
          { cmd: '/submissions approve', syntax: '/submissions approve submission_id:<id>', desc: 'Approves a submission', perm: 'Manage Server' },
          { cmd: '/submissions reject', syntax: '/submissions reject submission_id:<id> reason:<text>', desc: 'Rejects a submission', perm: 'Manage Server' },
        ],
      },
    ],
  },
  {
    id: 'community-marketplace',
    title: '8. Community & Marketplace',
    subs: [
      {
        title: 'Ads \u2014 /ad',
        rows: [
          { cmd: '/ad submit', syntax: '/ad submit company_name:<> title:<> description:<> ...', desc: 'Submits an ad for owner approval', perm: 'Anyone' },
          { cmd: '/ad status', syntax: '/ad status ad_id:<id>', desc: 'Checks status of an ad you submitted', perm: 'Anyone' },
          { cmd: '/ad pending', syntax: '/ad pending', desc: 'Lists ads awaiting approval', perm: 'Bot Owner' },
          { cmd: '/ad approve', syntax: '/ad approve ad_id:<id>', desc: 'Approves a pending ad', perm: 'Bot Owner' },
          { cmd: '/ad reject', syntax: '/ad reject ad_id:<id> reason:<text>', desc: 'Rejects a pending ad', perm: 'Bot Owner' },
          { cmd: '/ad active', syntax: '/ad active', desc: 'Shows currently approved/running ads', perm: 'Anyone' },
        ],
      },
      {
        title: 'Marketplace \u2014 /marketplace',
        rows: [
          { cmd: '/marketplace list', syntax: '/marketplace list name:<> title:<> description:<> price_usd:<> category:<>', desc: 'Lists a service you\u2019re offering for sale', perm: '' },
          { cmd: '/marketplace browse', syntax: '/marketplace browse', desc: 'Browses active service listings', perm: '' },
          { cmd: '/marketplace mine', syntax: '/marketplace mine', desc: 'Shows your own listings', perm: '' },
        ],
      },
      {
        title: 'Referrals \u2014 /referral',
        rows: [
          { cmd: '/referral mycode', syntax: '/referral mycode', desc: 'Gets your personal referral code', perm: '' },
          { cmd: '/referral use', syntax: '/referral use code:<code>', desc: 'Redeems someone else\u2019s referral code', perm: '' },
          { cmd: '/referral stats', syntax: '/referral stats', desc: 'Shows your referral count and tracked earnings (tracked only, not a real payout)', perm: '' },
        ],
      },
      {
        title: 'Bot Store \u2014 /botstore (directory of member-submitted bots)',
        rows: [
          { cmd: '/botstore submit', syntax: '/botstore submit ...', desc: 'Submits your bot to the directory', perm: '' },
          { cmd: '/botstore browse', syntax: '/botstore browse category:<optional>', desc: 'Browses submitted bots', perm: '' },
          { cmd: '/botstore trending', syntax: '/botstore trending', desc: 'Shows the most-clicked bots in the directory', perm: '' },
          { cmd: '/botstore mine', syntax: '/botstore mine', desc: 'Shows bots you\u2019ve submitted', perm: '' },
          { cmd: '/botstore search', syntax: '/botstore search query:<text>', desc: 'Searches the directory by keyword', perm: '' },
          { cmd: '/botstore rate', syntax: '/botstore rate listing_id:<id> stars:<1-5>', desc: 'Rates a bot in the directory', perm: '' },
        ],
      },
      {
        title: 'Bots Archive \u2014 /archive',
        rows: [
          { cmd: '/archive enable', syntax: '/archive enable', desc: 'Enables the archive system for this server', perm: 'Bot Owner' },
          { cmd: '/archive submit', syntax: '/archive submit ...', desc: 'Submits your bot to the archive by Application ID', perm: 'Anyone' },
          { cmd: '/archive pending', syntax: '/archive pending', desc: 'Shows submissions flagged for manual review', perm: 'Bot Owner' },
          { cmd: '/archive review', syntax: '/archive review', desc: 'Resolves flagged listings from a dropdown', perm: 'Bot Owner' },
          { cmd: '/archive resolve', syntax: '/archive resolve listing_id:<id> approve:<true/false> reason:<text>', desc: 'Approves or denies a flagged/disputed listing', perm: 'Bot Owner' },
          { cmd: '/archive bypass', syntax: '/archive bypass ...', desc: 'Force-approves a bot regardless of its risk score', perm: 'Bot Owner' },
          { cmd: '/archive webhook', syntax: '/archive webhook ...', desc: 'Adds, edits, or removes the webhook on your own listing', perm: 'Anyone' },
          { cmd: '/archive refresh', syntax: '/archive refresh listing_id:<id>', desc: 'Forces the posted card to re-sync with the current vote count', perm: 'Bot Owner' },
          { cmd: '/archive trending', syntax: '/archive trending', desc: 'Shows the current top bots in the archive', perm: 'Anyone' },
          { cmd: '/archive boost', syntax: '/archive boost listing_id:<id> tier:<>', desc: 'Features your approved listing at the top of the archive', perm: 'Anyone' },
        ],
      },
      {
        title: 'Discover Players \u2014 /discoverplayers',
        rows: [
          { cmd: '/discoverplayers create', syntax: '/discoverplayers create ...', desc: 'Creates a new Discover Players category', perm: '' },
          { cmd: '/discoverplayers join', syntax: '/discoverplayers join ...', desc: 'Joins a category', perm: '' },
          { cmd: '/discoverplayers browse', syntax: '/discoverplayers browse category:<optional>', desc: 'Lists categories, or the members of one specific category', perm: '' },
          { cmd: '/discoverplayers profile', syntax: '/discoverplayers profile ...', desc: 'Sets your profile (only shown to mutual matches)', perm: '' },
          { cmd: '/discoverplayers invite', syntax: '/discoverplayers invite category:<name>', desc: 'Gets a shareable link to join a category', perm: '' },
          { cmd: '/discoverplayers challenge', syntax: '/discoverplayers challenge user:<@user> category:<name>', desc: 'Challenges another member of a shared category', perm: '' },
          { cmd: '/discoverplayers upgrade', syntax: '/discoverplayers upgrade category:<name>', desc: 'Paid. Raises a category\u2019s member cap', perm: '' },
        ],
        footnote: 'All anyone can use.',
      },
    ],
  },
  {
    id: 'clones',
    title: '9. Owning Your Own Bot (Clones)',
    rows: [
      { cmd: '/registerclone', syntax: '/registerclone token:<your bot token>', desc: 'Registers your own bot token to run it as a clone of this bot (DM only)', perm: 'Anyone' },
      { cmd: '/myclones', syntax: '/myclones', desc: 'Lists the Discord bot clones you own', perm: 'Anyone' },
      { cmd: '/removeclone', syntax: '/removeclone clone_id:<id>', desc: 'Deactivates one of your clones (doesn\u2019t delete the underlying bot)', perm: 'Anyone' },
    ],
    subs: [
      {
        title: 'Clone Monetization \u2014 /clonemonetize',
        rows: [
          { cmd: '/clonemonetize status', syntax: '/clonemonetize status clone_id:<id>', desc: 'Checks monetization status for a clone you own', perm: 'Anyone' },
          { cmd: '/clonemonetize activate', syntax: '/clonemonetize activate clone_id:<optional>', desc: 'Starts or renews monetization on a clone', perm: 'Anyone' },
          { cmd: '/clonemonetize prices', syntax: '/clonemonetize prices clone_id:<id>', desc: 'Views the clone\u2019s current prices for paid features', perm: 'Anyone' },
          { cmd: '/clonemonetize setprice', syntax: '/clonemonetize setprice clone_id:<id> feature:<> amount_ghs:<n>', desc: 'Sets a custom price for one of the clone\u2019s paid features', perm: 'Anyone' },
          { cmd: '/clonemonetize payment', syntax: '/clonemonetize payment clone_id:<id>', desc: 'Checks where the clone\u2019s payments currently go', perm: 'Anyone' },
          { cmd: '/clonemonetize setpayment', syntax: '/clonemonetize setpayment clone_id:<id> provider:<>', desc: 'Routes the clone\u2019s payments to your own Paystack/Stripe key, or back to the main bot\u2019s', perm: 'Anyone' },
        ],
      },
      {
        title: 'Managing Bots by Token \u2014 /botmanager',
        rows: [
          { cmd: '/botmanager add', syntax: '/botmanager add token:<token>', desc: 'Registers a bot you own by pasting its token', perm: 'Anyone' },
          { cmd: '/botmanager list', syntax: '/botmanager list', desc: 'Lists your registered bots', perm: 'Anyone' },
          { cmd: '/botmanager view', syntax: '/botmanager view bot_id:<id>', desc: 'Views details of one registered bot', perm: 'Anyone' },
          { cmd: '/botmanager manage', syntax: '/botmanager manage', desc: 'Picks a registered bot from a dropdown and manages it', perm: 'Anyone' },
          { cmd: '/botmanager setname', syntax: '/botmanager setname bot_id:<id> username:<2-32 chars>', desc: 'Changes the bot\u2019s Discord username', perm: 'Anyone' },
          { cmd: '/botmanager setdescription', syntax: '/botmanager setdescription bot_id:<id> description:<up to 400 chars>', desc: 'Changes the bot\u2019s public description', perm: 'Anyone' },
          { cmd: '/botmanager setcommands', syntax: '/botmanager setcommands bot_id:<id> ...', desc: 'Overwrites the bot\u2019s global slash commands', perm: 'Anyone' },
          { cmd: '/botmanager remove', syntax: '/botmanager remove bot_id:<id>', desc: 'Unregisters a bot (doesn\u2019t stop the bot itself)', perm: 'Anyone' },
        ],
        footnote: 'All anyone can use, for bots they own.',
      },
    ],
  },
  {
    id: 'owner-only',
    title: '10. Owner-Only Commands (bot owner, not server admin)',
    intro: 'These only work for whoever owns the main PRIME-BOT deployment \u2014 not server administrators.',
    rows: [
      { cmd: '/admin stats', syntax: '/admin stats', desc: 'Bot-wide analytics', perm: 'Bot Owner' },
      { cmd: '/admin guilds', syntax: '/admin guilds', desc: 'Lists every server the bot is in, with join dates', perm: 'Bot Owner' },
      { cmd: '/admin submissions', syntax: '/admin submissions', desc: 'Reviews pending anime submissions', perm: 'Bot Owner' },
      { cmd: '/admin exportusers', syntax: '/admin exportusers', desc: 'Exports all user records as a CSV', perm: 'Bot Owner' },
      { cmd: '/admin envcheck', syntax: '/admin envcheck', desc: 'Sanity-checks required environment variables', perm: 'Bot Owner' },
      { cmd: '/admin revenue', syntax: '/admin revenue', desc: 'Revenue dashboard across all paid features', perm: 'Bot Owner' },
      { cmd: '/admin subscribers', syntax: '/admin subscribers', desc: 'Lists active Media Connect + premium-group subscribers', perm: 'Bot Owner' },
      { cmd: '/admin commissions', syntax: '/admin commissions', desc: 'Shows the commission split for monetized clone bots', perm: 'Bot Owner' },
      { cmd: '/admin clones', syntax: '/admin clones', desc: 'Manages active Discord bot clones', perm: 'Bot Owner' },
      { cmd: '/ownermonetize', syntax: '/ownermonetize clone_id:<id>', desc: 'Force-activates monetization on any clone, no payment required', perm: 'Bot Owner' },
      { cmd: '/ownerbroadcast', syntax: '/ownerbroadcast ...', desc: 'DMs an announcement to bot users or clone admins', perm: 'Bot Owner' },
      { cmd: '/broadcaststatus', syntax: '/broadcaststatus id:<optional>', desc: 'Checks whether an /ownerbroadcast actually went out', perm: 'Bot Owner' },
      { cmd: '/autopost setup', syntax: '/autopost setup channel:#chan interval:<hours>', desc: 'Turns on periodic bot self-promo posts in a channel', perm: 'Bot Owner' },
      { cmd: '/autopost disable', syntax: '/autopost disable', desc: 'Turns off periodic self-promo posts', perm: 'Bot Owner' },
      { cmd: '/autopost status', syntax: '/autopost status', desc: 'Checks this server\u2019s autopost config', perm: 'Bot Owner' },
      { cmd: '/autopostcontent add', syntax: '/autopostcontent add ...', desc: 'Adds a post to the autopost rotation library', perm: 'Bot Owner' },
      { cmd: '/autopostcontent list', syntax: '/autopostcontent list', desc: 'Lists the autopost content library', perm: 'Bot Owner' },
      { cmd: '/autopostcontent remove', syntax: '/autopostcontent remove content_id:<#>', desc: 'Removes a post from the rotation', perm: 'Bot Owner' },
    ],
  },
]

export const QUICK_REFERENCE = {
  title: 'Quick Reference: Where to Start',
  items: [
    { label: 'New server, first time setting the bot up:', code: '/serversetup' },
    { label: 'Just want to know what\u2019s available:', code: '/help' },
    {
      label: 'Ask the AI in plain English how to do something with the bot:',
      code: '/aichat',
      extra: '\u2014 it knows every command above and will tell you the exact syntax, but it can\u2019t run commands for you; you still type the slash command yourself.',
    },
    {
      label: 'Every command\u2019s live description and options are also visible in Discord itself',
      code: '/',
      extra: 'and start typing the command name to see Discord\u2019s own autocomplete and hints, which always match what\u2019s documented here.',
    },
  ],
  footer:
    'Nothing above is invented \u2014 this is the exact command set defined in the bot\u2019s code (modules/command_reference.py plus every cog file). If a command you expected isn\u2019t listed, it doesn\u2019t exist in this build.',
}
