"""
GET/POST backing endpoint for the Next.js automod dashboard (app/dashboard/
[guildId]/page.tsx) — spec §4 open question #5.

No user-account/OAuth system exists anywhere in this repo, so rather than
bolting one on for a single config page, auth is the same capability-token
model as database.py's discord_dashboard_tokens: the token IS the
credential, generated by /automod dashboard (which itself requires Manage
Server in Discord to run) and embedded in the link the admin was given.
Anyone with the link can read/write that guild's automod config — same
trust model as an unlisted Google Doc link. Do not log the token or expose
it anywhere other than the ephemeral Discord reply that generates it.

CORS is open (dashboard is a public static page hitting this from the
browser) but every request still requires a valid token bound to the
specific guild_id/clone_id being read or written — a valid token for guild A
cannot touch guild B's config.
"""
import json
import logging
from datetime import date, datetime
from http.server import BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs

from database import db

logger = logging.getLogger(__name__)


def _json_default(obj):
    """Fallback serializer for json.dumps — handles types returned by the
    DB driver (e.g. datetime/date columns) that aren't JSON-native."""
    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    raise TypeError(f"Object of type {obj.__class__.__name__} is not JSON serializable")

# Keys the dashboard is allowed to write. Mirrors _AUTOMOD_DEFAULTS in
# database.py — kept as an explicit allowlist here (rather than accepting
# arbitrary POST body keys) so a malformed/malicious request body can't
# write to columns this endpoint wasn't meant to expose.
WRITABLE_FIELDS = {
    "action", "timeout_minutes", "log_channel_id",
    "word_filter_enabled", "banned_words",
    "anti_invite_enabled", "anti_mention_enabled", "anti_mention_threshold",
    "spam_enabled", "spam_flood_threshold", "spam_flood_window_seconds",
    "min_account_age_hours",
}


async def _resolve(token: str, guild_id: int):
    """Returns True if token is valid AND bound to this exact guild_id,
    False otherwise. Deliberately doesn't distinguish "bad token" from
    "token for a different guild" in the response — both should just look
    like 403 to a caller probing token values."""
    resolved = await db.resolve_dashboard_token(token)
    if not resolved:
        return False, None
    if resolved["guild_id"] != guild_id:
        return False, None
    return True, resolved["clone_id"]


class handler(BaseHTTPRequestHandler):

    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def _json(self, status: int, payload: dict):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self._cors()
        self.end_headers()
        self.wfile.write(json.dumps(payload, default=_json_default).encode())

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.end_headers()

    def do_GET(self):
        import asyncio
        query = parse_qs(urlparse(self.path).query)
        token = query.get("token", [""])[0]
        guild_id_raw = query.get("guild_id", [""])[0]
        if not token or not guild_id_raw.isdigit():
            self._json(400, {"status": "error", "message": "Missing token or guild_id"})
            return
        guild_id = int(guild_id_raw)

        async def _run():
            ok, clone_id = await _resolve(token, guild_id)
            if not ok:
                return None
            return await db.get_automod_config(guild_id, clone_id=clone_id)

        try:
            config = asyncio.run(_run())
        except Exception as e:
            logger.error(f"[v0] discord_dashboard GET error: {e}")
            self._json(500, {"status": "error", "message": "Internal error"})
            return

        if config is None:
            self._json(403, {"status": "error", "message": "Invalid or unauthorized token"})
            return
        self._json(200, {"status": "ok", "config": config})

    def do_POST(self):
        import asyncio
        query = parse_qs(urlparse(self.path).query)
        token = query.get("token", [""])[0]
        guild_id_raw = query.get("guild_id", [""])[0]
        if not token or not guild_id_raw.isdigit():
            self._json(400, {"status": "error", "message": "Missing token or guild_id"})
            return
        guild_id = int(guild_id_raw)

        length = int(self.headers.get("Content-Length", 0))
        try:
            body = json.loads(self.rfile.read(length) or b"{}")
        except json.JSONDecodeError:
            self._json(400, {"status": "error", "message": "Invalid JSON body"})
            return

        fields = {k: v for k, v in body.items() if k in WRITABLE_FIELDS}
        if not fields:
            self._json(400, {"status": "error", "message": "No writable fields in body"})
            return

        async def _run():
            ok, clone_id = await _resolve(token, guild_id)
            if not ok:
                return None
            await db.set_automod_config(guild_id, clone_id=clone_id, **fields)
            return await db.get_automod_config(guild_id, clone_id=clone_id)

        try:
            config = asyncio.run(_run())
        except Exception as e:
            logger.error(f"[v0] discord_dashboard POST error: {e}")
            self._json(500, {"status": "error", "message": "Internal error"})
            return

        if config is None:
            self._json(403, {"status": "error", "message": "Invalid or unauthorized token"})
            return
        self._json(200, {"status": "ok", "config": config})
