# path: api/server_listings.py

"""
GET/POST backing endpoint for the public server directory
(app/servers/page.tsx, app/servers/submit/page.tsx). Same shape and same
auth model as api/discord_dashboard.py — see that file's docstring and
server_listing_tokens' comment in database.py's _create_tables for the full
reasoning; this is the short version:

- No user-account/OAuth system exists anywhere in this repo. A listing
  token is generated by the /servers slash command, which requires Manage
  Server AND can only be run inside a guild the bot is already in — so a
  valid token already proves the "bot confirmed in server" requirement.
  There is deliberately no separate approval step here.
- guild_name/guild_icon_url/member_count always come from the token record
  (captured server-side from interaction.guild when /servers ran), never
  from the client's request body, so a listing can't be spoofed with a fake
  identity while pointing invite_url somewhere else.

Two GET modes on the same endpoint, distinguished by whether `token` is
present:
  - No token -> public directory feed (anyone, no auth) for /servers.
  - token + guild_id -> that guild's prefill data (its Discord identity plus
    any already-saved invite_url/description/tags) for /servers/submit.

POST always requires token + guild_id and upserts the listing.

Caching: every read-only public GET mode below (the directory feed, a
single listing, its leaderboard, its similar-servers list) sets a
Cache-Control: s-maxage header via self._json(..., max_age=N). Vercel's
edge CDN then serves repeat requests for the same query string straight
from cache without this function running again — no DB hit at all on a
cache hit. Token-gated modes (prefill), the report/click-log POST-like
branches, and the pow_challenge endpoint deliberately never set max_age:
those must always run fresh (a stale prefill would show old form data, a
cached pow challenge could be replayed). Bump max_age here first if the
DB is still seeing too much traffic; only add a separate in-process cache
if that isn't enough, since this endpoint's serverless instances don't
reliably stay warm between requests anyway.
"""
import json
import logging
import re
from datetime import date, datetime
from http.server import BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs

from database import db
from pow_captcha import issue_challenge, verify_solution

logger = logging.getLogger(__name__)

MAX_DESCRIPTION_LEN = 300
MAX_TAGS = 5
MAX_TAG_LEN = 20

# Loose but real: some flavor of a Discord invite link. Not trying to
# validate the invite actually resolves (that would mean an outbound HTTP
# call on every submit) — just that it isn't obviously garbage.
_INVITE_RE = re.compile(r"^https?://(www\.)?(discord\.gg|discord\.com/invite)/\S+$", re.IGNORECASE)
# Captures just the code, used to watch that invite's use-count for
# referral-conversion tracking (see check_ref_conversion in database.py).
_INVITE_CODE_RE = re.compile(r"(?:discord\.gg|discord\.com/invite)/([^/?\s]+)", re.IGNORECASE)


def _extract_invite_code(invite_url: str) -> str | None:
    m = _INVITE_CODE_RE.search(invite_url)
    return m.group(1) if m else None


def _json_default(obj):
    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    raise TypeError(f"Object of type {obj.__class__.__name__} is not JSON serializable")


# JS's Number type is a float64, safely exact only up to 2**53 - 1.
# Discord snowflakes (guild_id, voter_id, etc.) are 64-bit and routinely
# exceed that, so shipping them as bare JSON numbers lets JSON.parse
# silently round them to the nearest representable float — e.g.
# 1538566465517781193 becomes 1538566465517781200 on the way into the
# browser. That single off-by-a-few-digits corruption is what sent a real
# vote to a guild_id that matched NO listing on the directory at all (see
# the vote-oauth logs). Recursively stringifying any int outside the safe
# range, right before every response goes out, fixes this for guild_id
# specifically and for any other snowflake field this endpoint returns or
# grows in future — no need to enumerate field names or trust every call
# site to remember to str() its own IDs.
_JS_MAX_SAFE_INT = 2 ** 53 - 1


def _stringify_large_ints(value):
    if isinstance(value, bool):
        return value
    if isinstance(value, int) and (value > _JS_MAX_SAFE_INT or value < -_JS_MAX_SAFE_INT):
        return str(value)
    if isinstance(value, dict):
        return {k: _stringify_large_ints(v) for k, v in value.items()}
    if isinstance(value, list):
        return [_stringify_large_ints(v) for v in value]
    return value


async def _resolve(token: str, guild_id: int):
    """Same shape as discord_dashboard.py's _resolve — doesn't distinguish
    "bad token" from "token for a different guild" in the response."""
    resolved = await db.resolve_listing_token(token)
    if not resolved:
        return False, None
    if resolved["guild_id"] != guild_id:
        return False, None
    return True, resolved


def _clean_tags(raw) -> list[str]:
    if not isinstance(raw, list):
        return []
    out = []
    for t in raw:
        t = str(t).strip().lstrip("#").lower()
        if t and t not in out:
            out.append(t[:MAX_TAG_LEN])
        if len(out) >= MAX_TAGS:
            break
    return out


class handler(BaseHTTPRequestHandler):

    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def _json(self, status: int, payload: dict, max_age: int | None = None):
        """max_age, when set, adds a public Cache-Control header so Vercel's
        edge CDN can serve repeat requests for identical query params
        without invoking this function (and therefore without hitting the
        DB) again. Only ever passed for read-only, non-personalized GET
        modes below — never for POST, never for anything keyed off a
        one-time token or captcha nonce, since caching those would either
        leak stale writes or let a challenge/signature be replayed.
        stale-while-revalidate lets a slightly-stale copy serve instantly
        while the CDN refreshes in the background, so filter changes still
        feel fast even on a cache miss."""
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        if max_age is not None:
            self.send_header(
                "Cache-Control",
                f"public, s-maxage={max_age}, stale-while-revalidate={max_age * 4}",
            )
        self._cors()
        self.end_headers()
        self.wfile.write(json.dumps(_stringify_large_ints(payload), default=_json_default).encode())

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.end_headers()

    def do_GET(self):
        import asyncio
        query = parse_qs(urlparse(self.path).query)
        token = query.get("token", [""])[0]
        ref = query.get("ref", [""])[0]

        # Mode 0b: single-listing public lookup, for the per-listing deep
        # link page (app/servers/[guildId]/page.tsx) and its OG meta tags.
        # No token — this is the same data anyone gets from the directory
        # feed, just narrowed to one guild instead of the whole list.
        if token == "" and query.get("listing_guild_id", [""])[0].isdigit():
            listing_guild_id = int(query["listing_guild_id"][0])

            async def _run_single():
                return await db.get_public_listing_by_guild(listing_guild_id)

            try:
                listing = asyncio.run(_run_single())
            except Exception as e:
                logger.error(f"[v0] server_listings single GET error: {e}")
                self._json(500, {"status": "error", "message": "Internal error"})
                return
            if listing is None:
                self._json(404, {"status": "error", "message": "No listing for that server"})
                return
            self._json(200, {"status": "ok", "listing": listing}, max_age=60)
            return

        # Mode 0: referral-boost click log. Fired by app/servers/page.tsx on
        # page load whenever the URL carries ?ref=<code> (i.e. someone
        # followed a listing's boost link). No auth, no session/cookie
        # needed — see check_ref_conversion in database.py for how this
        # later gets attributed to a join purely via invite use-count, no
        # visitor identity required. A bad/unknown ref_code just no-ops, we
        # don't want a broken link to 500 the page.
        if token == "" and ref and "guild_id" not in query:
            async def _run_click():
                await db.log_ref_click(ref)

            try:
                asyncio.run(_run_click())
            except Exception as e:
                logger.error(f"[v0] server_listings ref click log error: {e}")
            self._json(200, {"status": "ok"})
            return

        # Mode 0c: top-voter leaderboard for one listing, used by the
        # per-listing deep-link page. Public, read-only, no auth needed —
        # same privacy level as the vote count already shown everywhere.
        if token == "" and query.get("leaderboard_guild_id", [""])[0].isdigit():
            lb_guild_id = int(query["leaderboard_guild_id"][0])

            async def _run_leaderboard():
                return await db.get_top_voters(lb_guild_id, limit=10)

            try:
                voters = asyncio.run(_run_leaderboard())
            except Exception as e:
                logger.error(f"[v0] server_listings leaderboard GET error: {e}")
                self._json(500, {"status": "error", "message": "Internal error"})
                return
            self._json(200, {"status": "ok", "voters": voters}, max_age=60)
            return

        # Mode 0d: "similar servers" — up to 4 other listings sharing at
        # least one tag with the given guild, ranked the same as the main
        # directory feed. Used on the per-listing deep-link page.
        if token == "" and query.get("similar_to_guild_id", [""])[0].isdigit():
            similar_guild_id = int(query["similar_to_guild_id"][0])

            async def _run_similar():
                return await db.get_similar_listings(similar_guild_id, limit=4)

            try:
                similar = asyncio.run(_run_similar())
            except Exception as e:
                logger.error(f"[v0] server_listings similar GET error: {e}")
                self._json(500, {"status": "error", "message": "Internal error"})
                return
            self._json(200, {"status": "ok", "listings": similar}, max_age=120)
            return

        # Mode 0e: proof-of-work captcha challenge for the submit form —
        # see pow_captcha.py's docstring. No auth needed to request one,
        # it's cheap to issue and the signature is what protects it.
        if token == "" and query.get("pow_challenge", ["0"])[0] == "1":
            self._json(200, {"status": "ok", **issue_challenge()})
            return

        # Mode 1: public directory feed — no token needed. Accepts sort
        # (trending|votes|members|newest), tag (single tag filter), nsfw
        # (0/1 toggle), page + page_size for "load more" pagination.
        if not token:
            sort = query.get("sort", ["trending"])[0]
            tag = query.get("tag", [""])[0].strip().lstrip("#").lower() or None
            nsfw = query.get("nsfw", ["0"])[0] == "1"
            try:
                page = max(1, int(query.get("page", ["1"])[0]))
                page_size = min(60, max(1, int(query.get("page_size", ["24"])[0])))
            except ValueError:
                page, page_size = 1, 24

            async def _run_public():
                return await db.get_public_server_listings(
                    limit=page_size, offset=(page - 1) * page_size,
                    sort=sort, tag=tag, nsfw=nsfw,
                )

            try:
                result = asyncio.run(_run_public())
            except Exception as e:
                logger.error(f"[v0] server_listings public GET error: {e}")
                self._json(500, {"status": "error", "message": "Internal error"})
                return
            self._json(200, {
                "status": "ok",
                "listings": result["listings"],
                "total": result["total"],
                "page": page,
                "page_size": page_size,
            }, max_age=30)
            return

        # Mode 2: prefill data for the submit form — requires a valid token.
        guild_id_raw = query.get("guild_id", [""])[0]
        if not guild_id_raw.isdigit():
            self._json(400, {"status": "error", "message": "Missing guild_id"})
            return
        guild_id = int(guild_id_raw)

        async def _run_prefill():
            ok, resolved = await _resolve(token, guild_id)
            if not ok:
                return None
            existing = await db.get_server_listing(guild_id, clone_id=resolved["clone_id"])
            return {
                "guild_name": resolved["guild_name"],
                "guild_icon_url": resolved["guild_icon_url"],
                "member_count": resolved["member_count"],
                "invite_url": existing["invite_url"] if existing else "",
                "description": existing["description"] if existing else "",
                "tags": existing["tags"] if existing else [],
                "banner_url": existing["banner_url"] if existing else "",
            }

        try:
            data = asyncio.run(_run_prefill())
        except Exception as e:
            logger.error(f"[v0] server_listings prefill GET error: {e}")
            self._json(500, {"status": "error", "message": "Internal error"})
            return

        if data is None:
            self._json(403, {"status": "error", "message": "Invalid or unauthorized token"})
            return
        self._json(200, {"status": "ok", **data})

    def do_POST(self):
        import asyncio
        query = parse_qs(urlparse(self.path).query)

        # Report mode: distinguished by ?report=1, no token needed — this
        # is a public "flag this listing" action, not an edit. Kept as its
        # own branch rather than a new endpoint file since it shares CORS/
        # JSON helpers and the same guild_id-in-query convention.
        if query.get("report", ["0"])[0] == "1":
            report_guild_id_raw = query.get("guild_id", [""])[0]
            if not report_guild_id_raw.isdigit():
                self._json(400, {"status": "error", "message": "Missing guild_id"})
                return
            report_guild_id = int(report_guild_id_raw)
            length = int(self.headers.get("Content-Length", 0))
            try:
                body = json.loads(self.rfile.read(length) or b"{}")
            except json.JSONDecodeError:
                self._json(400, {"status": "error", "message": "Invalid JSON body"})
                return
            reason = str(body.get("reason", "")).strip()[:500]
            if not reason:
                self._json(400, {"status": "error", "message": "A reason is required"})
                return

            async def _run_report():
                await db.report_listing(report_guild_id, None, reason)

            try:
                asyncio.run(_run_report())
            except Exception as e:
                logger.error(f"[v0] server_listings report POST error: {e}")
                self._json(500, {"status": "error", "message": "Internal error"})
                return
            self._json(200, {"status": "ok"})
            return

        token = query.get("token", [""])[0]
        guild_id_raw = query.get("guild_id", [""])[0]
        if not token or not guild_id_raw.isdigit():
            self._json(400, {"status": "error", "message": "Missing token or guild_id"})
            return
        guild_id = int(guild_id_raw)

        length = int(self.headers.get("Content-Length", 0))
        try:
            body = json.loads(self.rfile.read(length) or b"{}")
        except json.JSONDecodeError:
            self._json(400, {"status": "error", "message": "Invalid JSON body"})
            return

        invite_url = str(body.get("invite_url", "")).strip()
        description = str(body.get("description", "")).strip()[:MAX_DESCRIPTION_LEN]
        tags = _clean_tags(body.get("tags"))
        banner_url = str(body.get("banner_url", "")).strip()[:500] or None
        if banner_url and not re.match(r"^https?://\S+$", banner_url, re.IGNORECASE):
            self._json(400, {"status": "error", "message": "Banner must be a valid image URL"})
            return

        # Proof-of-work captcha check — see pow_captcha.py. Required fields
        # come back exactly as issued by the pow_challenge GET mode above;
        # a missing/incomplete pow block is treated as a failed solve, not
        # skipped, so the frontend can't accidentally submit without it.
        pow_block = body.get("pow") or {}
        pow_reason = verify_solution(
            salt=str(pow_block.get("salt", "")),
            difficulty=int(pow_block.get("difficulty", 0) or 0),
            expires=int(pow_block.get("expires", 0) or 0),
            signature=str(pow_block.get("signature", "")),
            nonce=str(pow_block.get("nonce", "")),
        )
        if pow_reason is not None:
            logger.info(f"[v0] server_listings POST failed captcha check: {pow_reason}")
            self._json(400, {"status": "error", "message": "Captcha check failed — please try again"})
            return

        if not invite_url:
            self._json(400, {"status": "error", "message": "An invite link is required"})
            return
        if not _INVITE_RE.match(invite_url):
            self._json(400, {"status": "error", "message": "That doesn't look like a discord.gg or discord.com/invite link"})
            return

        async def _run():
            ok, resolved = await _resolve(token, guild_id)
            if not ok:
                return None
            listing = await db.upsert_server_listing(
                guild_id, resolved["clone_id"],
                resolved["guild_name"], resolved["guild_icon_url"], resolved["member_count"],
                invite_url, description, tags, banner_url,
            )
            # Referral-boost link is assigned lazily right after the listing
            # first exists (or on every re-save, idempotently — same code
            # path either way) rather than at token-mint time, since a
            # listing with no ref_code yet just means "not submitted".
            listing["ref_code"] = await db.ensure_listing_ref_code(guild_id, resolved["clone_id"])
            # Re-parsed on every save (not just creation) so editing the
            # invite link keeps conversion tracking pointed at the right
            # invite instead of silently watching a stale one.
            code = _extract_invite_code(invite_url)
            if code:
                await db.set_listing_invite_code(guild_id, resolved["clone_id"], code)
                listing["invite_code"] = code
            return listing

        try:
            listing = asyncio.run(_run())
        except Exception as e:
            logger.error(f"[v0] server_listings POST error: {e}")
            self._json(500, {"status": "error", "message": "Internal error"})
            return

        if listing is None:
            self._json(403, {"status": "error", "message": "Invalid or unauthorized token"})
            return
        self._json(200, {"status": "ok", "listing": listing})
