# path: api/server_listings.py

"""
GET/POST backing endpoint for the public server directory
(app/servers/page.tsx, app/servers/submit/page.tsx). Same shape and same
auth model as api/discord_dashboard.py — see that file's docstring and
server_listing_tokens' comment in database.py's _create_tables for the full
reasoning; this is the short version:

- No user-account/OAuth system exists anywhere in this repo. A listing
  token is generated by the /servers slash command, which requires Manage
  Server AND can only be run inside a guild the bot is already in — so a
  valid token already proves the "bot confirmed in server" requirement.
  There is deliberately no separate approval step here.
- guild_name/guild_icon_url/member_count always come from the token record
  (captured server-side from interaction.guild when /servers ran), never
  from the client's request body, so a listing can't be spoofed with a fake
  identity while pointing invite_url somewhere else.

Two GET modes on the same endpoint, distinguished by whether `token` is
present:
  - No token -> public directory feed (anyone, no auth) for /servers.
  - token + guild_id -> that guild's prefill data (its Discord identity plus
    any already-saved invite_url/description/tags) for /servers/submit.

POST always requires token + guild_id and upserts the listing.
"""
import json
import logging
import re
from datetime import date, datetime
from http.server import BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs

from database import db

logger = logging.getLogger(__name__)

MAX_DESCRIPTION_LEN = 300
MAX_TAGS = 5
MAX_TAG_LEN = 20

# Loose but real: some flavor of a Discord invite link. Not trying to
# validate the invite actually resolves (that would mean an outbound HTTP
# call on every submit) — just that it isn't obviously garbage.
_INVITE_RE = re.compile(r"^https?://(www\.)?(discord\.gg|discord\.com/invite)/\S+$", re.IGNORECASE)
# Captures just the code, used to watch that invite's use-count for
# referral-conversion tracking (see check_ref_conversion in database.py).
_INVITE_CODE_RE = re.compile(r"(?:discord\.gg|discord\.com/invite)/([^/?\s]+)", re.IGNORECASE)


def _extract_invite_code(invite_url: str) -> str | None:
    m = _INVITE_CODE_RE.search(invite_url)
    return m.group(1) if m else None


def _json_default(obj):
    if isinstance(obj, (datetime, date)):
        return obj.isoformat()
    raise TypeError(f"Object of type {obj.__class__.__name__} is not JSON serializable")


async def _resolve(token: str, guild_id: int):
    """Same shape as discord_dashboard.py's _resolve — doesn't distinguish
    "bad token" from "token for a different guild" in the response."""
    resolved = await db.resolve_listing_token(token)
    if not resolved:
        return False, None
    if resolved["guild_id"] != guild_id:
        return False, None
    return True, resolved


def _clean_tags(raw) -> list[str]:
    if not isinstance(raw, list):
        return []
    out = []
    for t in raw:
        t = str(t).strip().lstrip("#").lower()
        if t and t not in out:
            out.append(t[:MAX_TAG_LEN])
        if len(out) >= MAX_TAGS:
            break
    return out


class handler(BaseHTTPRequestHandler):

    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")

    def _json(self, status: int, payload: dict):
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self._cors()
        self.end_headers()
        self.wfile.write(json.dumps(payload, default=_json_default).encode())

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.end_headers()

    def do_GET(self):
        import asyncio
        query = parse_qs(urlparse(self.path).query)
        token = query.get("token", [""])[0]
        ref = query.get("ref", [""])[0]

        # Mode 0: referral-boost click log. Fired by app/servers/page.tsx on
        # page load whenever the URL carries ?ref=<code> (i.e. someone
        # followed a listing's boost link). No auth, no session/cookie
        # needed — see check_ref_conversion in database.py for how this
        # later gets attributed to a join purely via invite use-count, no
        # visitor identity required. A bad/unknown ref_code just no-ops, we
        # don't want a broken link to 500 the page.
        if token == "" and ref and "guild_id" not in query:
            async def _run_click():
                await db.log_ref_click(ref)

            try:
                asyncio.run(_run_click())
            except Exception as e:
                logger.error(f"[v0] server_listings ref click log error: {e}")
            self._json(200, {"status": "ok"})
            return

        # Mode 1: public directory feed — no token needed.
        if not token:
            async def _run_public():
                return await db.get_public_server_listings()

            try:
                listings = asyncio.run(_run_public())
            except Exception as e:
                logger.error(f"[v0] server_listings public GET error: {e}")
                self._json(500, {"status": "error", "message": "Internal error"})
                return
            self._json(200, {"status": "ok", "listings": listings})
            return

        # Mode 2: prefill data for the submit form — requires a valid token.
        guild_id_raw = query.get("guild_id", [""])[0]
        if not guild_id_raw.isdigit():
            self._json(400, {"status": "error", "message": "Missing guild_id"})
            return
        guild_id = int(guild_id_raw)

        async def _run_prefill():
            ok, resolved = await _resolve(token, guild_id)
            if not ok:
                return None
            existing = await db.get_server_listing(guild_id, clone_id=resolved["clone_id"])
            return {
                "guild_name": resolved["guild_name"],
                "guild_icon_url": resolved["guild_icon_url"],
                "member_count": resolved["member_count"],
                "invite_url": existing["invite_url"] if existing else "",
                "description": existing["description"] if existing else "",
                "tags": existing["tags"] if existing else [],
            }

        try:
            data = asyncio.run(_run_prefill())
        except Exception as e:
            logger.error(f"[v0] server_listings prefill GET error: {e}")
            self._json(500, {"status": "error", "message": "Internal error"})
            return

        if data is None:
            self._json(403, {"status": "error", "message": "Invalid or unauthorized token"})
            return
        self._json(200, {"status": "ok", **data})

    def do_POST(self):
        import asyncio
        query = parse_qs(urlparse(self.path).query)
        token = query.get("token", [""])[0]
        guild_id_raw = query.get("guild_id", [""])[0]
        if not token or not guild_id_raw.isdigit():
            self._json(400, {"status": "error", "message": "Missing token or guild_id"})
            return
        guild_id = int(guild_id_raw)

        length = int(self.headers.get("Content-Length", 0))
        try:
            body = json.loads(self.rfile.read(length) or b"{}")
        except json.JSONDecodeError:
            self._json(400, {"status": "error", "message": "Invalid JSON body"})
            return

        invite_url = str(body.get("invite_url", "")).strip()
        description = str(body.get("description", "")).strip()[:MAX_DESCRIPTION_LEN]
        tags = _clean_tags(body.get("tags"))

        if not invite_url:
            self._json(400, {"status": "error", "message": "An invite link is required"})
            return
        if not _INVITE_RE.match(invite_url):
            self._json(400, {"status": "error", "message": "That doesn't look like a discord.gg or discord.com/invite link"})
            return

        async def _run():
            ok, resolved = await _resolve(token, guild_id)
            if not ok:
                return None
            listing = await db.upsert_server_listing(
                guild_id, resolved["clone_id"],
                resolved["guild_name"], resolved["guild_icon_url"], resolved["member_count"],
                invite_url, description, tags,
            )
            # Referral-boost link is assigned lazily right after the listing
            # first exists (or on every re-save, idempotently — same code
            # path either way) rather than at token-mint time, since a
            # listing with no ref_code yet just means "not submitted".
            listing["ref_code"] = await db.ensure_listing_ref_code(guild_id, resolved["clone_id"])
            # Re-parsed on every save (not just creation) so editing the
            # invite link keeps conversion tracking pointed at the right
            # invite instead of silently watching a stale one.
            code = _extract_invite_code(invite_url)
            if code:
                await db.set_listing_invite_code(guild_id, resolved["clone_id"], code)
                listing["invite_code"] = code
            return listing

        try:
            listing = asyncio.run(_run())
        except Exception as e:
            logger.error(f"[v0] server_listings POST error: {e}")
            self._json(500, {"status": "error", "message": "Internal error"})
            return

        if listing is None:
            self._json(403, {"status": "error", "message": "Invalid or unauthorized token"})
            return
        self._json(200, {"status": "ok", "listing": listing})
